Feat/add entity
kraftenty/place-finder pull request #5
Opened 2023-11-18 15:25 UTC by kraftenty

## Done

-entity와 repository를 만듦
-entity와 repository 테스트 클래스 만들고, 돌려서 성공함
-데이터 검수(필수정보 누락된 행 삭제, 오타 수정, 위도&경도 삽입) 후 csv파일로 만듦

2023-11-18 17:07 UTC, Istiopaxx requested changes
1. 테스트 잘 썼습니다 앞으로도 계속 씁시다
2. 엔티티 클래스에서 setter 모두 삭제
3. application.yaml 파일은 .gitignore에 등록하는 편이 좋습니다 차후에 DB 호스팅을 한다면 DB 주소가 알려져선 안됩니다

엔티티 클래스들에 모두 AllArgsConstructor, NoArgsConstructor가 적용되어 있는데 나중에 빌더 패턴을 적용해서 생성하는 것도 고려해봅시다. 지금 해야되는건 아니고, 나중에 적용 ㄱㄱ

2023-11-18 17:07 UTC, Istiopaxx commented on src/main/java/com/placefinder/placefinder/entity/Library.java
> +@Setter
Lombok에 Getter, Setter 모두 통합해서 적용해주는 @Data 어노테이션 있는데 알고있는지? @Data 써도됩니다
그리고 엔티티 클래스에는 세터를 조심해서 만들어야 합니다 엔티티 객체의 상태를 마구마구 바꾸는 세터가 모두 퍼블릭 인터페이스로 열려있으면 실수로라도 엔티티의 상태를 바꿔서 DB에 업데이트되거나, 예상치 못한 side effect를 만들어낼 수 있습니다

Setter 어노테이션은 모두 없애는 걸 추천합니다

2023-11-18 17:07 UTC, Istiopaxx commented on src/main/java/com/placefinder/placefinder/entity/PublicFacility.java
> +@Getter @Setter
여기도 setter 없애기

2023-11-18 17:07 UTC, Istiopaxx commented on src/main/java/com/placefinder/placefinder/entity/Toilet.java
> +@Getter @Setter
여기도

2023-11-18 17:07 UTC, Istiopaxx commented on src/main/java/com/placefinder/placefinder/entity/Library.java
> +    public Library() { }
이런 인자가 없는 생성자를 자동으로 생성해주는 @NoArgsConstructor 어노테이션이 있습니다

2023-11-19 01:24 UTC, kraftenty commented on src/main/java/com/placefinder/placefinder/entity/Library.java
> +@Setter
세터에 그런 위험성이 있었네요.!! 모두 없애야 겠습니다.

2023-11-19 01:28 UTC, kraftenty commented on src/main/java/com/placefinder/placefinder/entity/Library.java
> +    public Library() { }
오 롬복은 정말 좋은게 많네요. 바로 적용하겠습니다

2023-11-20 10:22 UTC, Istiopaxx approved these changes
LGTM 👍🏿

2023-11-20 10:23 UTC, Istiopaxx commented
늦게봐서 미안합니다~~ 까먹고있엇네요~~ 머지하면 될것 같습니다~~

2023-11-20 10:28 UTC, kraftenty commented
머지 하겠습니다~!

2023-11-20 10:31 UTC, merged